auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            HuangMin.com
url:              http://mhctseu.github.com
feed:             /atom.xml
author:
name:             HuangMin 
description:      "HuangMin\'s Blog"

copyright:
    - Design by <a title="HuangMin" target="_blank">HuangMin</a> &copy; 2013
